### PR TITLE
Fix bug with image and flavor cache.

### PR DESCRIPTION
**Pull request by chrislovsund**
There was only one cache for all clusters to share, now that is fixed, and there is one cache per cluster.
Refactoring of OSClient access
It is improved how sending health messages back to the server works.
Merge PendingAgentsService into OpenStackInstances.  …
Refactor PluginSettings.
Generalize Testing functions.
Add more performance metrics.

### CODE REVIEW

**Comment by tomzo** [comment]
Hi @chrislovsund 
I've merged your PR and updated CI system just now.
Please be advised that there was a quite annoying bug in the test resources. You've probably developed the code on case-insensitive filesystem (Mac or Windows), and therefore the tests were failing on Linux. The fix was https://github.com/gocd-contrib/openstack-elastic-agent/commit/b7136a1a3f966e03b5e1528001ec86c50ad7b8c9 which merely changes the casing of files to exactly match with requested resource names.
Would you mind testing version `0.14.2` and letting me know if that's stable?

As I said earlier, I don't have an openstack cluster to test it myself, so your feedback is quite critical for maintenance of this plugin.

**Comment by chrislovsund** [comment]
Ok, thanks I will test that fix.

**Comment by chrislovsund** [comment]
Seems to stable to me after a two days of usage.

**Comment by tomzo** [comment]
@chrislovsund thanks for feedback

**Pull request merged**
