### PR TITLE
Fix for bug "Images with an empty name breaks the creation of new elastic agents"

### PR DESCRIPTION
**Pull request by chrislovsund**
Probable fix for #7

### CODE REVIEW

**Comment by chrislovsund** [comment]
It seems I did something strange during pull request back and forth. `build.gradle` shouldn't conflict.

**Comment by tomzo** [comment]
@chrislovsund can you try to rebase on master? Barrow's last commit shouldn't be in this PR, that why there is a conflict.

**Comment by chrislovsund** [comment]
Looks like the conflict have been solved now.

**Comment by tomzo** [comment]
@chrislovsund I meant that you should reduce number of commits to cleanup, not add more of them.
It can be done by [rebasing](https://git-scm.com/book/en/v2/Git-Branching-Rebasing).
I have done this for you and merged already.
```sh
$ git remote -v
chris	git@github.com:chrislovsund/openstack-elastic-agent.git (fetch)
chris	git@github.com:chrislovsund/openstack-elastic-agent.git (push)
origin	git@github.com:gocd-contrib/openstack-elastic-agent.git (fetch)
origin	git@github.com:gocd-contrib/openstack-elastic-agent.git (push)
$ git fetch chris
$ git fetch origin
$ git checkout chris/master
$ git rebase origin/master
# The you could have git push chris master -f , which would have fixed this PR
```

**Comment by chrislovsund** [comment]
ok, thanks for the help.

**Pull request closed without merging**
