### PR TITLE
Fix for #15 that will log ERROR and throw checked exception,

### PR DESCRIPTION
**Pull request by chrislovsund**
instead of throwing uncaught unchecked exception.
Bump version to 0.12.1

### CODE REVIEW

**Comment by tomzo** [comment]
Looks OK, although version bump is unnecessary, we haven't released 0.12.0 yet

**Comment by chrislovsund** [comment]
Ok, should I recommit with 0.12.0?

**Comment by tomzo** [comment]
> Ok, should I recommit with 0.12.0?

yes please

**Comment by chrislovsund** [comment]
version bump removed.

**Comment by tomzo** [comment]
Great. Thanks a lot for the fix.

**Pull request merged**
